variables:
  - template: eng/common-variables.yml
  - name: Build.Repository.Clean
    value: true
  - name: _HelixType
    value: build/product
  - name: _HelixSource
    value: pr/dotnet/xharness/$(Build.SourceBranch)
  - name: _HelixTestType
    value: test/product/
  - name: _XUnitProject
    value: $(Build.SourcesDirectory)/tests/XHarness.Tests/XHarness.Tests.csproj
  - name: _XUnitTargetFramework
    value: netcoreapp3.1
  - name: _XUnitRunnerVersion
    value: 2.4.1
  - name: _DotNetCliPackageType
    value: sdk
  - name: _DotNetCliVersion
    value: 3.1.101
  - name: _HelixAccessToken
    value: ''

# CI and PR triggers
trigger:
  batch: true
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

stages:
- stage: build
  displayName: Build
  jobs:
  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      enableTelemetry: true
      enablePublishBuildArtifacts: true
      enableMicrobuild: true
      enablePublishUsingPipelines: true
      enablePublishBuildAssets: true
      helixRepo: dotnet/xharness

      jobs:
      - job: OSX
        pool:
          name: Hosted macOS
        strategy:
          matrix:
            Debug:
              _BuildConfig: Debug
        steps:
        - script: eng/common/cibuild.sh
            --configuration $(_BuildConfig)
            --prepareMachine
            $(_InternalBuildArgs)
          name: Build
          displayName: Build
          condition: succeeded()

        - publish: $(Build.SourcesDirectory)/artifacts/packages/$(_BuildConfig)/Shipping
          artifact: Microsoft.DotNet.XHarness.CLI
        
        - bash: cp tests/integration-tests/run-ios-tests.sh artifacts/packages/$(_BuildConfig)/Shipping
          displayName: Copy test scripts
          workingDirectory: $(Build.SourcesDirectory)

- stage: test
  displayName: Run integration tests
  dependsOn: build
  jobs:
  - job: integration_tests
    displayName: Integration tests
    pool:
        name: Hosted macOS
    steps:
    - download: current
      artifact: Microsoft.DotNet.XHarness.CLI

    - template: /eng/common/templates/steps/send-to-helix.yml
      displayName: Run tests on iOS
      parameters:
        DisplayNamePrefix: Run Tests
        HelixBaseUri: https://helix.int-dot.net/
        HelixType: test/product/
        IncludeDotNetCli: true
        DotNetCliPackageType: runtime
        DotNetCliVersion: 2.1.403
        WaitForWorkItemCompletion: true
        HelixTargetQueues: OSX.1015.Amd64.Open # TODO: Change this
        Creator: xharness
        WorkItemDirectory: $(Pipeline.Workspace)/Microsoft.DotNet.XHarness.CLI
        WorkItemCommand: chmod 0755 run-ios-tests.sh && ./run-ios-tests.sh
        WorkItemTimeout: 120
